c0ae580f65b378f7786e6d19c6158761c8b0c4b6
==================================================
Fix https://bz.apache.org/bugzilla/show_bug.cgi?id=58692
==================================================
Mark Thomas
==================================================
Wed Dec 16 20:53:39 2015 +0000
==================================================
StandardJarScanner.java
Fix https://bz.apache.org/bugzilla/show_bug.cgi?id=58692
Make StandardJarScanner more robust. Log a warning if a class path entry cannot be scanned rather than triggering the failure of the web application. Includes a test case written by Derek Abdine.

git-svn-id: https://svn.apache.org/repos/asf/tomcat/trunk@1720448 13f79535-47bb-0310-9956-ffa450edef68



==================================================
TestStandardJarScanner.java
index 5777f43862..14b0e41bc0 100644
--- a/java/org/apache/tomcat/util/scan/StandardJarScanner.java
+++ b/java/org/apache/tomcat/util/scan/StandardJarScanner.java
@@ -20,7 +20,6 @@ import java.io.File;
 import java.io.IOException;
 import java.net.JarURLConnection;
 import java.net.MalformedURLException;
-import java.net.URISyntaxException;
 import java.net.URL;
 import java.net.URLClassLoader;
 import java.net.URLConnection;
@@ -36,6 +35,7 @@ import org.apache.tomcat.JarScanFilter;
 import org.apache.tomcat.JarScanType;
 import org.apache.tomcat.JarScanner;
 import org.apache.tomcat.JarScannerCallback;
+import org.apache.tomcat.util.ExceptionUtils;
 import org.apache.tomcat.util.res.StringManager;
 
 /**
@@ -336,10 +336,11 @@ public class StandardJarScanner implements JarScanner {
                                 }
                             }
                         }
-                    } catch (URISyntaxException e) {
+                    } catch (Throwable t) {
+                        ExceptionUtils.handleThrowable(t);
                         // Wrap the exception and re-throw
                         IOException ioe = new IOException();
-                        ioe.initCause(e);
+                        ioe.initCause(t);
                         throw ioe;
                     }
                 }

==================================================
